apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../applications/vault
patches:
- path: values-patch.yaml
- target:
    kind: HelmRelease
    name: vault
  patch: |
    - op: add
      path: /spec/kubeConfig
      value:
        secretRef:
          name: opossum-kubeconfig
